//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meeting
    {
        public int Id { get; set; }
        public Nullable<int> Reciever { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public Nullable<int> Sender { get; set; }
        public string text { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
